/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAdvisorRouteImport } from './routes/_app.advisor'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppBudgetsRouteImport } from './routes/_app.budgets'
import { Route as AppCashFlowRouteImport } from './routes/_app.cash-flow'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppLedgerRouteImport } from './routes/_app.ledger'
import { Route as AppRiskRouteImport } from './routes/_app.risk'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppVendorsRouteImport } from './routes/_app.vendors'
import { Route as AppInvoicesIdRouteImport } from './routes/_app.invoices_.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorRoute = AppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppCashFlowRoute = AppCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices_/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/advisor': typeof AppAdvisorRoute
  '/audit': typeof AppAuditRoute
  '/budgets': typeof AppBudgetsRoute
  '/cash-flow': typeof AppCashFlowRoute
  '/invoices': typeof AppInvoicesRoute
  '/ledger': typeof AppLedgerRoute
  '/risk': typeof AppRiskRoute
  '/settings': typeof AppSettingsRoute
  '/vendors': typeof AppVendorsRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/advisor': typeof AppAdvisorRoute
  '/audit': typeof AppAuditRoute
  '/budgets': typeof AppBudgetsRoute
  '/cash-flow': typeof AppCashFlowRoute
  '/invoices': typeof AppInvoicesRoute
  '/ledger': typeof AppLedgerRoute
  '/risk': typeof AppRiskRoute
  '/settings': typeof AppSettingsRoute
  '/vendors': typeof AppVendorsRoute
  '/': typeof AppIndexRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/advisor': typeof AppAdvisorRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/cash-flow': typeof AppCashFlowRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/ledger': typeof AppLedgerRoute
  '/_app/risk': typeof AppRiskRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/vendors': typeof AppVendorsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/invoices_/$id': typeof AppInvoicesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/advisor'
    | '/audit'
    | '/budgets'
    | '/cash-flow'
    | '/invoices'
    | '/ledger'
    | '/risk'
    | '/settings'
    | '/vendors'
    | '/invoices/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/advisor'
    | '/audit'
    | '/budgets'
    | '/cash-flow'
    | '/invoices'
    | '/ledger'
    | '/risk'
    | '/settings'
    | '/vendors'
    | '/'
    | '/invoices/$id'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/advisor'
    | '/_app/audit'
    | '/_app/budgets'
    | '/_app/cash-flow'
    | '/_app/invoices'
    | '/_app/ledger'
    | '/_app/risk'
    | '/_app/settings'
    | '/_app/vendors'
    | '/_app/'
    | '/_app/invoices_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advisor': {
      id: '/_app/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AppAdvisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-flow': {
      id: '/_app/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof AppCashFlowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger': {
      id: '/_app/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk': {
      id: '/_app/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices_/$id': {
      id: '/_app/invoices_/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdvisorRoute: typeof AppAdvisorRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppCashFlowRoute: typeof AppCashFlowRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppRiskRoute: typeof AppRiskRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvisorRoute: AppAdvisorRoute,
  AppAuditRoute: AppAuditRoute,
  AppBudgetsRoute: AppBudgetsRoute,
  AppCashFlowRoute: AppCashFlowRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppRiskRoute: AppRiskRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppIndexRoute: AppIndexRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
